"""add more slippy columns

Revision ID: 474f3ed46f73
Revises: 2221190f2759
Create Date: 2019-03-25 06:32:49.930335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474f3ed46f73'
down_revision = '2221190f2759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slippy_tiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_image', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('inference_ran', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('inference_timestamp', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slippy_tiles', schema=None) as batch_op:
        batch_op.drop_column('inference_timestamp')
        batch_op.drop_column('inference_ran')
        batch_op.drop_column('has_image')

    # ### end Alembic commands ###
