"""add centroid distance index

Revision ID: d9ccb1fc3ced
Revises: f78c5b7d4a52
Create Date: 2019-03-29 08:57:01.226643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ccb1fc3ced'
down_revision = 'f78c5b7d4a52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slippy_tiles', schema=None) as batch_op:
        batch_op.create_index('centroid_index', ['polygon_name', 'centroid_distance'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slippy_tiles', schema=None) as batch_op:
        batch_op.drop_index('centroid_index')

    # ### end Alembic commands ###
