"""add osm solar node table

Revision ID: f78c5b7d4a52
Revises: a8825815024c
Create Date: 2019-03-28 22:02:12.405302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78c5b7d4a52'
down_revision = 'a8825815024c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('osm_solar_nodes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('osm_solar_nodes',
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('longitude', 'latitude', sqlite_on_conflict='IGNORE')
    )
    # ### end Alembic commands ###
